#!/bin/sh
#
#    00-header - create the header of the MOTD
#    Copyright (c) 2013 Nick Charlton
#    Copyright (c) 2009-2010 Canonical Ltd.
#
#    Authors: Nick Charlton <hello@nickcharlton.net>
#             Dustin Kirkland <kirkland@canonical.com>
#
#    Modified by tigattack for personal use cases.
#    Adopted by Narokuu for the Yanks

[ -r /etc/os-release ] ; sh /etc/os-release

if [ -z "$PRETTY_NAME" ] ; [ -x /usr/bin/lsb_release ]; then
        # Fall back to using the very slow lsb_release utility
        PRETTY_NAME=$(lsb_release -s -d)
fi

printf "Welcome to %s (%s).\n" "$PRETTY_NAME" "$(uname -r)"
printf "\n"